name: Dependency Scanning

on: [push, pull_request]
jobs:
  dep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dep-scan
        run: |
          pip install owasp-depscan
          depscan --src . --reports-dir ./reports
      - uses: actions/upload-artifact@v4   # <- UPDATED HERE
        with:
          name: dep-scan-report
          path: ./reports
