name: Dependency Scanning

on: [push, pull_request]

jobs:
  dep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dep-scan and run
        run: |
          pip install owasp-depscan
          depscan --src . -v
