name: depscan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  depscan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare reports directory
      run: mkdir -p ${{ github.workspace }}/reports

    - name: Run depscan
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          ghcr.io/owasp-dep-scan/dep-scan \
          --src /app \
          --reports-dir /app/reports \
          -t nodejs \
          --profile research \
          --reachability-analyzer SemanticReachability \
          --explain \
          --debug

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: depscan-reports
        path: ${{ github.workspace }}/reports
