name: Dependency Scanning

on: [push, pull_request]

jobs:
  dep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dep-scan and run
        run: |
          pip install owasp-depscan
          depscan --src . --reports-dir ./reports -v
      - name: Upload dep-scan report
        uses: actions/upload-artifact@v4
        with:
          name: dep-scan-report
          path: ./reports
